processors += wdc65816 spc700 arm7tdmi gsu hg51b upd96050

objects += sfc-interface sfc-system sfc-controller
objects += sfc-cartridge sfc-memory
objects += sfc-cpu sfc-smp sfc-dsp sfc-ppu
objects += sfc-expansion sfc-satellaview sfc-21fx
objects += sfc-icd sfc-mcc sfc-dip sfc-event
objects += sfc-sa1 sfc-superfx
objects += sfc-armdsp sfc-hitachidsp sfc-necdsp
objects += sfc-epsonrtc sfc-sharprtc
objects += sfc-spc7110 sfc-sdd1
objects += sfc-obc1 sfc-msu1
objects += sfc-bsmemory sfc-sufamiturbo

obj/sfc-interface.o:   sfc/interface/interface.cpp
obj/sfc-system.o:      sfc/system/system.cpp
obj/sfc-controller.o:  sfc/controller/controller.cpp
obj/sfc-cartridge.o:   sfc/cartridge/cartridge.cpp
obj/sfc-memory.o:      sfc/memory/memory.cpp

obj/sfc-cpu.o:         sfc/cpu/cpu.cpp
obj/sfc-smp.o:         sfc/smp/smp.cpp
obj/sfc-dsp.o:         sfc/dsp/dsp.cpp
obj/sfc-ppu.o:         sfc/ppu/ppu.cpp

obj/sfc-expansion.o:   sfc/expansion/expansion.cpp
obj/sfc-satellaview.o: sfc/expansion/satellaview/satellaview.cpp
obj/sfc-21fx.o:        sfc/expansion/21fx/21fx.cpp

obj/sfc-icd.o:         sfc/coprocessor/icd/icd.cpp
obj/sfc-mcc.o:         sfc/coprocessor/mcc/mcc.cpp
obj/sfc-dip.o:         sfc/coprocessor/dip/dip.cpp
obj/sfc-event.o:       sfc/coprocessor/event/event.cpp

obj/sfc-sa1.o:         sfc/coprocessor/sa1/sa1.cpp
obj/sfc-superfx.o:     sfc/coprocessor/superfx/superfx.cpp

obj/sfc-armdsp.o:      sfc/coprocessor/armdsp/armdsp.cpp
obj/sfc-hitachidsp.o:  sfc/coprocessor/hitachidsp/hitachidsp.cpp
obj/sfc-necdsp.o:      sfc/coprocessor/necdsp/necdsp.cpp

obj/sfc-epsonrtc.o:    sfc/coprocessor/epsonrtc/epsonrtc.cpp
obj/sfc-sharprtc.o:    sfc/coprocessor/sharprtc/sharprtc.cpp

obj/sfc-spc7110.o:     sfc/coprocessor/spc7110/spc7110.cpp
obj/sfc-sdd1.o:        sfc/coprocessor/sdd1/sdd1.cpp
obj/sfc-obc1.o:        sfc/coprocessor/obc1/obc1.cpp

obj/sfc-msu1.o:        sfc/coprocessor/msu1/msu1.cpp

obj/sfc-bsmemory.o:    sfc/slot/bsmemory/bsmemory.cpp
obj/sfc-sufamiturbo.o: sfc/slot/sufamiturbo/sufamiturbo.cpp
