namespace hiro {
  #include "../resource/resource.hpp"
  #include "fixed-layout.hpp"
  #include "horizontal-layout.hpp"
  #include "vertical-layout.hpp"
  #include "table-layout.hpp"
  #include "horizontal-resize-grip.hpp"
  #include "vertical-resize-grip.hpp"
  #include "list-view.hpp"
  #include "shared.hpp"
  #include "message-dialog.hpp"
  #include "name-dialog.hpp"
  #include "browser-dialog.hpp"
  #include "about-dialog.hpp"
}
