processors += v30mz

objects += ws-interface ws-system
objects += ws-memory ws-eeprom ws-cartridge
objects += ws-cpu ws-ppu ws-apu

obj/ws-interface.o: ws/interface/interface.cpp
obj/ws-system.o:    ws/system/system.cpp
obj/ws-memory.o:    ws/memory/memory.cpp
obj/ws-eeprom.o:    ws/eeprom/eeprom.cpp
obj/ws-cartridge.o: ws/cartridge/cartridge.cpp
obj/ws-cpu.o:       ws/cpu/cpu.cpp
obj/ws-ppu.o:       ws/ppu/ppu.cpp
obj/ws-apu.o:       ws/apu/apu.cpp
