freebsd-x86_64-binaries_task:
    freebsd_instance:
        image_family: freebsd-12-2

    setup_script:
        - pkg install --yes gmake gdb gcc8 pkgconf sdl2 openal-soft gtk3 gtksourceview3 libXv zip

    compile_script:
        - gmake -C bsnes local=false

    package_script:
        - mkdir bsnes-nightly
        - mkdir bsnes-nightly/Database
        - mkdir bsnes-nightly/Firmware
        - cp -a bsnes/out/bsnes bsnes-nightly/bsnes
        - cp -a bsnes/Database/* bsnes-nightly/Database
        - cp -a shaders bsnes-nightly/Shaders
        - cp -a GPLv3.txt bsnes-nightly
        - cp -a extras/* bsnes-nightly
        - zip -r bsnes-nightly.zip bsnes-nightly

    bsnes-nightly_artifacts:
        path: "bsnes-nightly.zip"
