linux-x86_64-binaries_task:
    container:
        image: ubuntu:latest

    setup_script:
        - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential libgtk2.0-dev libpulse-dev mesa-common-dev libgtksourceview2.0-dev libcairo2-dev libsdl2-dev libxv-dev libao-dev libopenal-dev libudev-dev zip

    compile_script:
        - make -C bsnes local=false

    package_script:
        - mkdir bsnes-nightly
        - mkdir bsnes-nightly/Database
        - mkdir bsnes-nightly/Firmware
        - cp -a bsnes/out/bsnes bsnes-nightly/bsnes
        - cp -a bsnes/Database/* bsnes-nightly/Database
        - cp -a shaders bsnes-nightly/Shaders
        - cp -a GPLv3.txt bsnes-nightly
        - cp -a extras/* bsnes-nightly
        - zip -r bsnes-nightly.zip bsnes-nightly

    bsnes-nightly_artifacts:
        path: "bsnes-nightly.zip"

freebsd-x86_64-binaries_task:
    freebsd_instance:
        image_family: freebsd-12-2

    setup_script:
        - pkg install --yes gmake gdb gcc8 pkgconf sdl2 openal-soft gtksourceview2 libXv zip

    compile_script:
        - gmake -C bsnes local=false

    package_script:
        - mkdir bsnes-nightly
        - mkdir bsnes-nightly/Database
        - mkdir bsnes-nightly/Firmware
        - cp -a bsnes/out/bsnes bsnes-nightly/bsnes
        - cp -a bsnes/Database/* bsnes-nightly/Database
        - cp -a shaders bsnes-nightly/Shaders
        - cp -a GPLv3.txt bsnes-nightly
        - cp -a extras/* bsnes-nightly
        - zip -r bsnes-nightly.zip bsnes-nightly

    bsnes-nightly_artifacts:
        path: "bsnes-nightly.zip"

windows-x86_64-binaries_task:
    container:
        image: ubuntu:latest

    setup_script:
        - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential mingw-w64 zip

    compile_script:
        - make -C bsnes local=false platform=windows compiler="x86_64-w64-mingw32-g++" windres="x86_64-w64-mingw32-windres"

    package_script:
        - mkdir bsnes-nightly
        - mkdir bsnes-nightly/Database
        - mkdir bsnes-nightly/Firmware
        - cp -a bsnes/out/bsnes.exe bsnes-nightly/bsnes.exe
        - cp -a bsnes/Database/* bsnes-nightly/Database
        - cp -a shaders bsnes-nightly/Shaders
        - cp -a GPLv3.txt bsnes-nightly
        - cp -a extras/* bsnes-nightly
        - zip -r bsnes-nightly.zip bsnes-nightly

    bsnes-nightly_artifacts:
        path: "bsnes-nightly.zip"

macOS-x86_64-binaries_task:
    osx_instance:
        image: mojave-base

    compile_script:
        - make -C bsnes local=false

    package_script:
        - mkdir bsnes-nightly
        - cp -a bsnes/out/bsnes.app bsnes-nightly
        - cp -a GPLv3.txt bsnes-nightly
        - cp -a extras/* bsnes-nightly
        - zip -r bsnes-nightly.zip bsnes-nightly

    bsnes-nightly_artifacts:
        path: "bsnes-nightly.zip"
