SOURCES_C   := $(CORE_DIR)/gb.c \
					$(CORE_DIR)/apu.c \
					$(CORE_DIR)/memory.c \
					$(CORE_DIR)/mbc.c \
					$(CORE_DIR)/timing.c \
					$(CORE_DIR)/display.c \
					$(CORE_DIR)/symbol_hash.c \
					$(CORE_DIR)/debugger.c \
					$(CORE_DIR)/camera.c \
					$(CORE_DIR)/z80_cpu.c \
					$(CORE_DIR)/z80_disassembler.c \
					$(CORE_DIR)/joypad.c \
					$(LIBRETRO_DIR)/libretro.c
					