processors += huc6280

objects += pce-interface
objects += pce-cpu pce-vpc pce-vce pce-vdc pce-psg
objects += pce-system pce-cartridge
objects += pce-controller

obj/pce-interface.o:  pce/interface/interface.cpp
obj/pce-cpu.o:        pce/cpu/cpu.cpp
obj/pce-vpc.o:        pce/vpc/vpc.cpp
obj/pce-vce.o:        pce/vce/vce.cpp
obj/pce-vdc.o:        pce/vdc/vdc.cpp
obj/pce-psg.o:        pce/psg/psg.cpp
obj/pce-system.o:     pce/system/system.cpp
obj/pce-cartridge.o:  pce/cartridge/cartridge.cpp
obj/pce-controller.o: pce/controller/controller.cpp
