all:
	sourcery resource.bml resource.cpp resource.hpp

permissions:
	chmod +w icon/action/*.png
	chmod +w icon/application/*.png
	chmod +w icon/device/*.png
	chmod +w icon/edit/*.png
	chmod +w icon/emblem/*.png
	chmod +w icon/go/*.png
	chmod +w icon/media/*.png
	chmod +w icon/place/*.png
	chmod +w icon/prompt/*.png
