map("Escape", VK_ESCAPE);
map("F1", VK_F1);
map("F2", VK_F2);
map("F3", VK_F3);
map("F4", VK_F4);
map("F5", VK_F5);
map("F6", VK_F6);
map("F7", VK_F7);
map("F8", VK_F8);
map("F9", VK_F9);
map("F10", VK_F10);
map("F11", VK_F11);
map("F12", VK_F12);

map("PrintScreen", VK_SNAPSHOT);
map("ScrollLock", VK_SCROLL);
map("Pause", VK_PAUSE);

map("Insert", VK_INSERT);
map("Delete", VK_DELETE);
map("Home", VK_HOME);
map("End", VK_END);
map("PageUp", VK_PRIOR);
map("PageDown", VK_NEXT);

map("Up", VK_UP);
map("Down", VK_DOWN);
map("Left", VK_LEFT);
map("Right", VK_RIGHT);

map("Grave", VK_OEM_3);
map("1", '1');
map("2", '2');
map("3", '3');
map("4", '4');
map("5", '5');
map("6", '6');
map("7", '7');
map("8", '8');
map("9", '9');
map("0", '0');
map("Dash", VK_OEM_MINUS);
map("Equal", VK_OEM_PLUS);
map("Backspace", VK_BACK);

map("Tab", VK_TAB);
map("CapsLock", VK_CAPITAL);
map("LeftEnter", VK_RETURN);
map("LeftShift", VK_LSHIFT);
map("RightShift", VK_RSHIFT);
map("LeftControl", VK_LCONTROL);
map("RightControl", VK_RCONTROL);
map("LeftAlt", VK_LMENU);
map("RightAlt", VK_RMENU);
map("LeftSuper", VK_LWIN);
map("RightSuper", VK_RWIN);
map("Menu", VK_APPS);
map("Space", VK_SPACE);

map("OpenBracket", VK_OEM_4);
map("CloseBracket", VK_OEM_6);
map("Backslash", VK_OEM_5);
map("Semicolon", VK_OEM_1);
map("Apostrophe", VK_OEM_7);
map("Comma", VK_OEM_COMMA);
map("Period", VK_OEM_PERIOD);
map("Slash", VK_OEM_2);

map("A", 'A');
map("B", 'B');
map("C", 'C');
map("D", 'D');
map("E", 'E');
map("F", 'F');
map("G", 'G');
map("H", 'H');
map("I", 'I');
map("J", 'J');
map("K", 'K');
map("L", 'L');
map("M", 'M');
map("N", 'N');
map("O", 'O');
map("P", 'P');
map("Q", 'Q');
map("R", 'R');
map("S", 'S');
map("T", 'T');
map("U", 'U');
map("V", 'V');
map("W", 'W');
map("X", 'X');
map("Y", 'Y');
map("Z", 'Z');

map("NumLock", VK_NUMLOCK);
map("Divide", VK_DIVIDE);
map("Multiply", VK_MULTIPLY);
map("Subtract", VK_SUBTRACT);
map("Add", VK_ADD);
//map("RightEnter", ...);
map("Point", VK_DECIMAL);

map("One", VK_NUMPAD1);
map("Two", VK_NUMPAD2);
map("Three", VK_NUMPAD3);
map("Four", VK_NUMPAD4);
map("Five", VK_NUMPAD5);
map("Six", VK_NUMPAD6);
map("Seven", VK_NUMPAD7);
map("Eight", VK_NUMPAD8);
map("Nine", VK_NUMPAD9);
map("Zero", VK_NUMPAD0);

map("Shift", VK_LSHIFT, VK_RSHIFT);
map("Control", VK_LCONTROL, VK_RCONTROL);
map("Alt", VK_LMENU, VK_RMENU);
map("Super", VK_LWIN, VK_RWIN);
map("Enter", VK_RETURN);
