processors += arm7tdmi

objects += gba-memory gba-interface gba-system
objects += gba-cartridge gba-player
objects += gba-cpu gba-ppu gba-apu

obj/gba-memory.o:    gba/memory/memory.cpp
obj/gba-interface.o: gba/interface/interface.cpp
obj/gba-system.o:    gba/system/system.cpp
obj/gba-cartridge.o: gba/cartridge/cartridge.cpp
obj/gba-player.o:    gba/player/player.cpp
obj/gba-cpu.o:       gba/cpu/cpu.cpp
obj/gba-ppu.o:       gba/ppu/ppu.cpp
obj/gba-apu.o:       gba/apu/apu.cpp
