processors += mos6502

objects += fc-interface fc-system fc-controller
objects += fc-memory fc-cartridge fc-cpu fc-apu fc-ppu

obj/fc-interface.o:  fc/interface/interface.cpp
obj/fc-system.o:     fc/system/system.cpp
obj/fc-controller.o: fc/controller/controller.cpp
obj/fc-memory.o:     fc/memory/memory.cpp
obj/fc-cartridge.o:  fc/cartridge/cartridge.cpp
obj/fc-cpu.o:        fc/cpu/cpu.cpp
obj/fc-apu.o:        fc/apu/apu.cpp
obj/fc-ppu.o:        fc/ppu/ppu.cpp
