processors += z80

objects += msx-interface msx-system msx-cartridge
objects += msx-cpu msx-vdp msx-psg

obj/msx-interface.o: msx/interface/interface.cpp
obj/msx-system.o:    msx/system/system.cpp
obj/msx-cartridge.o: msx/cartridge/cartridge.cpp
obj/msx-cpu.o:       msx/cpu/cpu.cpp
obj/msx-vdp.o:       msx/vdp/vdp.cpp
obj/msx-psg.o:       msx/psg/psg.cpp
