void bCPU::exec_opcode() {
byte op;
  op = op_read();
  switch(op) {
/* 0x */
  case 0x00:op_brk();      break;
  case 0x01:op_ora_idpx(); break;
  case 0x02:op_cop();      break;
  case 0x03:op_ora_sr();   break;
  case 0x04:op_tsb_dp();   break;
  case 0x05:op_ora_dp();   break;
  case 0x06:op_asl_dp();   break;
  case 0x07:op_ora_ildp(); break;
  case 0x08:op_php();      break;
  case 0x09:op_ora_const();break;
  case 0x0a:op_asl();      break;
  case 0x0b:op_phd();      break;
  case 0x0c:op_tsb_addr(); break;
  case 0x0d:op_ora_addr(); break;
  case 0x0e:op_asl_addr(); break;
  case 0x0f:op_ora_long(); break;
/* 1x */
  case 0x10:op_bpl();      break;
  case 0x11:op_ora_idpy(); break;
  case 0x12:op_ora_idp();  break;
  case 0x13:op_ora_isry(); break;
  case 0x14:op_trb_dp();   break;
  case 0x15:op_ora_dpx();  break;
  case 0x16:op_asl_dpx();  break;
  case 0x17:op_ora_ildpy();break;
  case 0x18:op_clc();      break;
  case 0x19:op_ora_addry();break;
  case 0x1a:op_inc();      break;
  case 0x1b:op_tcs();      break;
  case 0x1c:op_trb_addr(); break;
  case 0x1d:op_ora_addrx();break;
  case 0x1e:op_asl_addrx();break;
  case 0x1f:op_ora_longx();break;
/* 2x */
  case 0x20:op_jsr_addr(); break;
  case 0x21:op_and_idpx(); break;
  case 0x22:op_jsr_long(); break;
  case 0x23:op_and_sr();   break;
  case 0x24:op_bit_dp();   break;
  case 0x25:op_and_dp();   break;
  case 0x26:op_rol_dp();   break;
  case 0x27:op_and_ildp(); break;
  case 0x28:op_plp();      break;
  case 0x29:op_and_const();break;
  case 0x2a:op_rol();      break;
  case 0x2b:op_pld();      break;
  case 0x2c:op_bit_addr(); break;
  case 0x2d:op_and_addr(); break;
  case 0x2e:op_rol_addr(); break;
  case 0x2f:op_and_long(); break;
/* 3x */
  case 0x30:op_bmi();      break;
  case 0x31:op_and_idpy(); break;
  case 0x32:op_and_idp();  break;
  case 0x33:op_and_isry(); break;
  case 0x34:op_bit_dpx();  break;
  case 0x35:op_and_dpx();  break;
  case 0x36:op_rol_dpx();  break;
  case 0x37:op_and_ildpy();break;
  case 0x38:op_sec();      break;
  case 0x39:op_and_addry();break;
  case 0x3a:op_dec();      break;
  case 0x3b:op_tsc();      break;
  case 0x3c:op_bit_addrx();break;
  case 0x3d:op_and_addrx();break;
  case 0x3e:op_rol_addrx();break;
  case 0x3f:op_and_longx();break;
/* 4x */
  case 0x40:op_rti();      break;
  case 0x41:op_eor_idpx(); break;
  case 0x42:op_wdm();      break;
  case 0x43:op_eor_sr();   break;
  case 0x44:op_mvp();      break;
  case 0x45:op_eor_dp();   break;
  case 0x46:op_lsr_dp();   break;
  case 0x47:op_eor_ildp(); break;
  case 0x48:op_pha();      break;
  case 0x49:op_eor_const();break;
  case 0x4a:op_lsr();      break;
  case 0x4b:op_phk();      break;
  case 0x4c:op_jmp_addr(); break;
  case 0x4d:op_eor_addr(); break;
  case 0x4e:op_lsr_addr(); break;
  case 0x4f:op_eor_long(); break;
/* 5x */
  case 0x50:op_bvc();      break;
  case 0x51:op_eor_idpy(); break;
  case 0x52:op_eor_idp();  break;
  case 0x53:op_eor_isry(); break;
  case 0x54:op_mvn();      break;
  case 0x55:op_eor_dpx();  break;
  case 0x56:op_lsr_dpx();  break;
  case 0x57:op_eor_ildpy();break;
  case 0x58:op_cli();      break;
  case 0x59:op_eor_addry();break;
  case 0x5a:op_phy();      break;
  case 0x5b:op_tcd();      break;
  case 0x5c:op_jmp_long(); break;
  case 0x5d:op_eor_addrx();break;
  case 0x5e:op_lsr_addrx();break;
  case 0x5f:op_eor_longx();break;
/* 6x */
  case 0x60:op_rts();      break;
  case 0x61:op_adc_idpx(); break;
  case 0x62:op_per();      break;
  case 0x63:op_adc_sr();   break;
  case 0x64:op_stz_dp();   break;
  case 0x65:op_adc_dp();   break;
  case 0x66:op_ror_dp();   break;
  case 0x67:op_adc_ildp(); break;
  case 0x68:op_pla();      break;
  case 0x69:op_adc_const();break;
  case 0x6a:op_ror();      break;
  case 0x6b:op_rtl();      break;
  case 0x6c:op_jmp_iaddr();break;
  case 0x6d:op_adc_addr(); break;
  case 0x6e:op_ror_addr(); break;
  case 0x6f:op_adc_long(); break;
/* 7x */
  case 0x70:op_bvs();       break;
  case 0x71:op_adc_idpy();  break;
  case 0x72:op_adc_idp();   break;
  case 0x73:op_adc_isry();  break;
  case 0x74:op_stz_dpx();   break;
  case 0x75:op_adc_dpx();   break;
  case 0x76:op_ror_dpx();   break;
  case 0x77:op_adc_ildpy(); break;
  case 0x78:op_sei();       break;
  case 0x79:op_adc_addry(); break;
  case 0x7a:op_ply();       break;
  case 0x7b:op_tdc();       break;
  case 0x7c:op_jmp_iaddrx();break;
  case 0x7d:op_adc_addrx(); break;
  case 0x7e:op_ror_addrx(); break;
  case 0x7f:op_adc_longx(); break;
/* 8x */
  case 0x80:op_bra();      break;
  case 0x81:op_sta_idpx(); break;
  case 0x82:op_brl();      break;
  case 0x83:op_sta_sr();   break;
  case 0x84:op_sty_dp();   break;
  case 0x85:op_sta_dp();   break;
  case 0x86:op_stx_dp();   break;
  case 0x87:op_sta_ildp(); break;
  case 0x88:op_dey();      break;
  case 0x89:op_bit_const();break;
  case 0x8a:op_txa();      break;
  case 0x8b:op_phb();      break;
  case 0x8c:op_sty_addr(); break;
  case 0x8d:op_sta_addr(); break;
  case 0x8e:op_stx_addr(); break;
  case 0x8f:op_sta_long(); break;
/* 9x */
  case 0x90:op_bcc();      break;
  case 0x91:op_sta_idpy(); break;
  case 0x92:op_sta_idp();  break;
  case 0x93:op_sta_isry(); break;
  case 0x94:op_sty_dpx();  break;
  case 0x95:op_sta_dpx();  break;
  case 0x96:op_stx_dpy();  break;
  case 0x97:op_sta_ildpy();break;
  case 0x98:op_tya();      break;
  case 0x99:op_sta_addry();break;
  case 0x9a:op_txs();      break;
  case 0x9b:op_txy();      break;
  case 0x9c:op_stz_addr(); break;
  case 0x9d:op_sta_addrx();break;
  case 0x9e:op_stz_addrx();break;
  case 0x9f:op_sta_longx();break;
/* ax */
  case 0xa0:op_ldy_const();break;
  case 0xa1:op_lda_idpx(); break;
  case 0xa2:op_ldx_const();break;
  case 0xa3:op_lda_sr();   break;
  case 0xa4:op_ldy_dp();   break;
  case 0xa5:op_lda_dp();   break;
  case 0xa6:op_ldx_dp();   break;
  case 0xa7:op_lda_ildp(); break;
  case 0xa8:op_tay();      break;
  case 0xa9:op_lda_const();break;
  case 0xaa:op_tax();      break;
  case 0xab:op_plb();      break;
  case 0xac:op_ldy_addr(); break;
  case 0xad:op_lda_addr(); break;
  case 0xae:op_ldx_addr(); break;
  case 0xaf:op_lda_long(); break;
/* bx */
  case 0xb0:op_bcs();      break;
  case 0xb1:op_lda_idpy(); break;
  case 0xb2:op_lda_idp();  break;
  case 0xb3:op_lda_isry(); break;
  case 0xb4:op_ldy_dpx();  break;
  case 0xb5:op_lda_dpx();  break;
  case 0xb6:op_ldx_dpy();  break;
  case 0xb7:op_lda_ildpy();break;
  case 0xb8:op_clv();      break;
  case 0xb9:op_lda_addry();break;
  case 0xba:op_tsx();      break;
  case 0xbb:op_tyx();      break;
  case 0xbc:op_ldy_addrx();break;
  case 0xbd:op_lda_addrx();break;
  case 0xbe:op_ldx_addry();break;
  case 0xbf:op_lda_longx();break;
/* cx */
  case 0xc0:op_cpy_const();break;
  case 0xc1:op_cmp_idpx(); break;
  case 0xc2:op_rep();      break;
  case 0xc3:op_cmp_sr();   break;
  case 0xc4:op_cpy_dp();   break;
  case 0xc5:op_cmp_dp();   break;
  case 0xc6:op_dec_dp();   break;
  case 0xc7:op_cmp_ildp(); break;
  case 0xc8:op_iny();      break;
  case 0xc9:op_cmp_const();break;
  case 0xca:op_dex();      break;
  case 0xcb:op_wai();      break;
  case 0xcc:op_cpy_addr(); break;
  case 0xcd:op_cmp_addr(); break;
  case 0xce:op_dec_addr(); break;
  case 0xcf:op_cmp_long(); break;
/* dx */
  case 0xd0:op_bne();       break;
  case 0xd1:op_cmp_idpy();  break;
  case 0xd2:op_cmp_idp();   break;
  case 0xd3:op_cmp_isry();  break;
  case 0xd4:op_pei();       break;
  case 0xd5:op_cmp_dpx();   break;
  case 0xd6:op_dec_dpx();   break;
  case 0xd7:op_cmp_ildpy(); break;
  case 0xd8:op_cld();       break;
  case 0xd9:op_cmp_addry(); break;
  case 0xda:op_phx();       break;
  case 0xdb:op_stp();       break;
  case 0xdc:op_jmp_iladdr();break;
  case 0xdd:op_cmp_addrx(); break;
  case 0xde:op_dec_addrx(); break;
  case 0xdf:op_cmp_longx(); break;
/* ex */
  case 0xe0:op_cpx_const();break;
  case 0xe1:op_sbc_idpx(); break;
  case 0xe2:op_sep();      break;
  case 0xe3:op_sbc_sr();   break;
  case 0xe4:op_cpx_dp();   break;
  case 0xe5:op_sbc_dp();   break;
  case 0xe6:op_inc_dp();   break;
  case 0xe7:op_sbc_ildp(); break;
  case 0xe8:op_inx();      break;
  case 0xe9:op_sbc_const();break;
  case 0xea:op_nop();      break;
  case 0xeb:op_xba();      break;
  case 0xec:op_cpx_addr(); break;
  case 0xed:op_sbc_addr(); break;
  case 0xee:op_inc_addr(); break;
  case 0xef:op_sbc_long(); break;
/* fx */
  case 0xf0:op_beq();       break;
  case 0xf1:op_sbc_idpy();  break;
  case 0xf2:op_sbc_idp();   break;
  case 0xf3:op_sbc_isry();  break;
  case 0xf4:op_pea();       break;
  case 0xf5:op_sbc_dpx();   break;
  case 0xf6:op_inc_dpx();   break;
  case 0xf7:op_sbc_ildpy(); break;
  case 0xf8:op_sed();       break;
  case 0xf9:op_sbc_addry(); break;
  case 0xfa:op_plx();       break;
  case 0xfb:op_xce();       break;
  case 0xfc:op_jsr_iaddrx();break;
  case 0xfd:op_sbc_addrx(); break;
  case 0xfe:op_inc_addrx(); break;
  case 0xff:op_sbc_longx(); break;
  }

  snes->notify(SNES::CPU_EXEC_OPCODE);
}
